### PR TITLE
Chapter 4 transcription

### PR DESCRIPTION
**Pull request by gregmacfarlane**

### CODE REVIEW

**Comment by gregmacfarlane** [comment]
- [x] @camlunt is going to be doing the initial copy/past on this one

**Comment by camlunt** [comment]
Chapter 4 is a long one, so I would recommend getting a head start!

**Assignments for Chapter 4**
*Don't forget to also update any in-text references to the figures, tables, and equations that you're in charge of.*

@SamKLau:
- [x] Tables 4-1 and 4-2
- [x] Figure 4.3
- [x] Equations 4.1-4.18

@barnesmaxmax:
- [x] Tables 4-3 through 4-6
- [x] Equations 4.19-4.35
- [x] Equations 4.60-4.64

@loganbennett93:
- [x] Tables 4-7 and 4-8
- [x] Figure 4.7
- [x] Equations 4.36-4.42
- [x] Equations 4.55-4.59

@bwang0601:
- [x] Tables 4-9 through 4-12
- [x] Figures 4.5-4.6 (I'm pretty sure these are copy/paste ones)
- [x] Equations 4.43-4.54
- [x] Equations 4.69-4.74

@camlunt:
- [x] Equations 4.65-4.68 
- [x] the unnumbered tables/lists on pages 43, 44, and 59
- [x] footnotes

@gregmacfarlane, can you confirm which figures are copy/paste? I'm thinking Figure 4.5 and 4.6 are for sure, but I don't want to give Bruce (or anyone else) false hope haha

**Comment by SamKLau** [comment]
@gregmacfarlane what should we do for footnotes? there was a footnote in chapter 3 and many in chapter 4

**Comment by SamKLau** [comment]
> @gregmacfarlane what should we do for footnotes? there was a footnote in chapter 3 and many in chapter 4

I also am curious about referencing other chapters and sections

**Pull request merged**
